language: php

php:
  - 7.1
  - 7.2
  - 7.3

before_install:
  - composer self-update
  - composer clear-cache

install:
  - travis_retry composer update --no-interaction --no-ansi --no-progress --no-suggest --optimize-autoloader --prefer-stable

script:
  - ./vendor/bin/phpcs src --standard=PSR2 -n src
  - ./vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  on_success: never
  on_failure: always
